[package]
name = "setup-mc"
version = "1.0"
edition = "2021"
license = "GPL-3.0-or-later"

[dependencies]
figlet-rs = "0.1.5"
reqwest = { version = "0.12.9", features = ["json"] }
serde_json = "1.0.133"
sysinfo = "0.33.0"
tokio = { version = "1.41.1", features = ["full"] }
